### PR TITLE
Assignment2

### PR DESCRIPTION
**Pull request by DominicAlvarez**
Complete the following Tutorials and do not clean up resources until assignment is graded.

Create Web App {[https://learn.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net70&pivots=development-environment-cli}](https://learn.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net70&pivots=development-environment-cli%7D) Note: Deploy application code using az cli, not the VSCode extension
Web App Created ✅ (You can use the below steps to publish your app OR use the 'az webapp up' command in the above tutorial)

Run command from your terminal 'dotnet publish SampleApp/MyFirstAzureWebApp'. This builds the application and files are genearted in SampleApp/MyFirstAzureWebApp/bin/Debug/net7.0/publish folder
Zip the items in your created publish folder
Use 'az webapp deploy' command to deploy your zip file to the application
Url Accessible ✅

Create and Connect Storage Account - Using Azure CLI when option is available {[https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-storage?tabs=azure-cli}](https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-storage?tabs=azure-cli%7D)
Enabled Managed Identity on Web App ✅
Created Storage Account ✅
Web App Granted Access to Storage Account ✅
Create a Key Vault https://learn.microsoft.com/en-us/azure/key-vault/general/quick-create-cli https://learn.microsoft.com/en-us/azure/app-service/app-service-configuration-references#granting-your-app-access-to-referenced-key-vaults https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli
Key Vault Created ✅
Key Vault Secret Created ✅
Key Vault Access policy created for user '[jcurry9@ewu.edu](mailto:jcurry9@ewu.edu)' with secret 'Get' permission ✅
Web App Granted Access to Key Vault ✅
Reference key vault secret as an app setting on your web app where the app setting name is the secret name and the value references your secret using the secret uri ❌ (https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli#source-app-settings-from-key-vault)
Create a PowerShell script called Assignment2.ps1 on your branch within the Assignment2 folder ✅

### CODE REVIEW

**Comment by AndrewKorchemniy** [comment]
I ran into something similar with the script failing to pass on the final check.
The grading script expects the following for the secret uri:

"@Microsoft.KeyVault(SecretUri=https://$KeyVault.vault.azure.net/secrets/$SecretName/)"

Notably, the expected secret uri format does not include the version of the secret. This can trip you up since by default, if you just copy the uri from the vault secret viewer, it will include the version appended at the end of the uri. Simply remove the version number within the application setting and you should be good!

**Comment by jenny-curry** [comment]
Please give my azure account jcurry9@ewu.edu contributor access over your subscription. Thanks!

**Comment by jenny-curry** [comment]
Create Web App {[https://learn.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net70&pivots=development-environment-cli}](https://learn.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net70&pivots=development-environment-cli%7D) Note: Deploy application code using az cli, not the VSCode extension
Web App Created ✅ (You can use the below steps to publish your app OR use the 'az webapp up' command in the above tutorial)

Run command from your terminal 'dotnet publish SampleApp/MyFirstAzureWebApp'. This builds the application and files are genearted in SampleApp/MyFirstAzureWebApp/bin/Debug/net7.0/publish folder
Zip the items in your created publish folder
Use 'az webapp deploy' command to deploy your zip file to the application
Url Accessible ✅

Create and Connect Storage Account - Using Azure CLI when option is available {[https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-storage?tabs=azure-cli}](https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-storage?tabs=azure-cli%7D)
Enabled Managed Identity on Web App ✅
Created Storage Account ✅
Web App Granted Access to Storage Account ✅
Create a Key Vault https://learn.microsoft.com/en-us/azure/key-vault/general/quick-create-cli https://learn.microsoft.com/en-us/azure/app-service/app-service-configuration-references#granting-your-app-access-to-referenced-key-vaults https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli
Key Vault Created ✅
Key Vault Secret Created ❌
Key Vault Access policy created for user '[jcurry9@ewu.edu](mailto:jcurry9@ewu.edu)' with secret 'Get' permission ❌
Web App Granted Access to Key Vault ❌
Reference key vault secret as an app setting on your web app where the app setting name is the secret name and the value references your secret using the secret uri ❌ (https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli#source-app-settings-from-key-vault)
Create a PowerShell script called Assignment2.ps1 on your branch within the Assignment2 folder ✅
-----------------------------------------------------------------------------------------------------------------------------------

This is what I got when grading. 
image

**Comment by jenny-curry** [comment]
If you send me a screen shot of the access policy and your secret created, I can update your grade, I was not able to see the resources from my portal

**Comment by jenny-curry** [comment]
Create Web App {[https://learn.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net70&pivots=development-environment-cli}](https://learn.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net70&pivots=development-environment-cli%7D) Note: Deploy application code using az cli, not the VSCode extension
Web App Created ✅ (You can use the below steps to publish your app OR use the 'az webapp up' command in the above tutorial)

Run command from your terminal 'dotnet publish SampleApp/MyFirstAzureWebApp'. This builds the application and files are genearted in SampleApp/MyFirstAzureWebApp/bin/Debug/net7.0/publish folder
Zip the items in your created publish folder
Use 'az webapp deploy' command to deploy your zip file to the application
Url Accessible ✅

Create and Connect Storage Account - Using Azure CLI when option is available {[https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-storage?tabs=azure-cli}](https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-storage?tabs=azure-cli%7D)
Enabled Managed Identity on Web App ✅
Created Storage Account ✅
Web App Granted Access to Storage Account ✅
Create a Key Vault https://learn.microsoft.com/en-us/azure/key-vault/general/quick-create-cli https://learn.microsoft.com/en-us/azure/app-service/app-service-configuration-references#granting-your-app-access-to-referenced-key-vaults https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli
Key Vault Created ✅
Key Vault Secret Created  ✅
Key Vault Access policy created for user '[jcurry9@ewu.edu](mailto:jcurry9@ewu.edu)' with secret 'Get' permission  ✅
Web App Granted Access to Key Vault  ✅
Reference key vault secret as an app setting on your web app where the app setting name is the secret name and the value references your secret using the secret uri ❌ (https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli#source-app-settings-from-key-vault)
Create a PowerShell script called Assignment2.ps1 on your branch within the Assignment2 folder ✅

**Pull request closed without merging**
