### PR TITLE
Assignment1-Beighlor M

### PR DESCRIPTION
**Pull request by bluebandit95**
Sorry for all the commits,
Final product, has imgs,
and subscription id are both at bottom. 
Thanks!

### CODE REVIEW

**Comment by jenny-curry** [comment]
@bluebandit95 Could you add you Assignment 1 values to your ps1 file for grading? Please do ASAP as grades are due Tuesday.

**Comment by bluebandit95** [comment]
Yeah, by add values, are you wanting my client ID, tenure id, and subscription ID?
I think right now it just has subscription ID in the Assignment 1.ps1, then screenshots of the action log workflow and the certificate.
________________________________

**Comment by jenny-curry** [comment]
@bluebandit95 Oh I see I was thinking this assignment had values with it, my bad. Nothing needed on your end at the moment.

**Comment by jenny-curry** [comment]
1. Fork class repository ✅
2. Create Assignment 1 Branch and Sync branch from class repo ✅
3. Clone your repo/branch to your computer
4. Set Up Azure following SettingUpAzure.md ✅
5. Create a script called Assignment1.ps1 in the Assignment1 folder ✅
   - Set a variable named subscription_id in your PowerShell file and set the value as a string your subscription ID. ✅
6. Create an App ID with a property of your repo name ✅
7. Add the App ID as a contributor to your subscription ✅
8. Create Assignment1.yml Action (in the workflows folder) ✅

- Authenticate to Azure ✅
- List resources in the subscription ✅

**Pull request closed without merging**
